export const NATIVE_API = "nativeApi";
export const IPC_KEYS = {
    REQUEST_PORTS_LIST: "REQUEST_PORTS_LIST_IPC",
    GET_PORTS_LIST_RESPONSE: "GET_PORTS_LIST_RESPONSE_IPC",
    CONNECT_SERIAL: "CONNECT_SERIAL_IPC",
    GET_CONNECT_SERIAL_RESULT: "GET_CONNECT_SERIAL_RESULT_IPC",
    SEND_SERIAL_MESSAGE: "SEND_SERIAL_MESSAGE_IPC",
    GET_SERIAL_RESPONSE: "GET_SERIAL_RESPONSE_IPC",
} as const;